/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dwqpduylhwrgwirxrvjv";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3cXBkdXlsaHdyZ3dpcnhydmp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxNDc0OTAsImV4cCI6MjA4MTcyMzQ5MH0.swsnuQhVnH6rkNoRM4qQRKcmkgwaL_cw4KkwCvVm1Wg";
